add 200, 400 and 404 tests
kyrikoni/kk-backend-portfolio-project pull request #4
Opened 2022-12-14 10:51 UTC by kyrikoni

2022-12-14 10:58 UTC, popatre requested changes

2022-12-14 10:58 UTC, popatre commented on __tests__/app.test.js
> +        expect(msg).toBe("no user found");
Message wise - as they've entered a review id, it would be make sense to be `id not found`, or review id not found

presume your docs will mention needing a review id, then this message will say something about a user not found - which could be confusing

2022-12-14 10:58 UTC, popatre commented on __tests__/app.test.js
>    });
Could you add another test please?

- [ ]  200 for an review that exists but has no comments - return an empty array

2022-12-14 10:58 UTC, popatre commented on models/app.models.js
> +        msg: "no user found",
no id found

2022-12-14 10:58 UTC, popatre commented on models/app.models.js
> +  ORDER BY comments.created_at DESC
Im not sure what this join is doing. 
The comments already have an review id on them, you can literally just select the comments with the id you want, without any join

2022-12-14 10:58 UTC, popatre commented on models/app.models.js
> +  ORDER BY comments.created_at DESC
I dont think you're using anything from the review table, even when they are joined

2022-12-15 10:18 UTC, robert112233 approved these changes
Merge 👍  Great work !

2022-12-15 10:18 UTC, robert112233 commented on controllers/app.controllers.js
> +  Promise.all([checkReviewIdExists(reviewId), selectComments(reviewId)])
Great way to differentiate between invalid article and valid article but with no comments 👍

2022-12-15 10:19 UTC, merged